server:
  port: 6770
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    url: jdbc:mysql://116.198.200.0:3306/mall_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  cloud:
    nacos:
      discovery:
        server-addr: 116.198.200.0:8848
        namespace: 9b648059-4aae-4965-8cc4-6b758b4b6f73
        group: SEATA_GROUP

rocketmq:
  name-server: 47.100.41.27:9876
  producer:
    group: mall-default-producer-group # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 1 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 1 # 异步发送消息失败重试次数，默认2

#seata:
#  application-id: seata-server
#  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），
#  # 要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
#  tx-service-group: order-tx-service-group
#  service:
#    vgroup-mapping:
#      order-tx-service-group: default
#  config:
#    type: nacos
#    # 需要和server在同一个注册中心下
#    nacos:
#      namespace: 9b648059-4aae-4965-8cc4-6b758b4b6f73
#      serverAddr: 116.198.200.0:8848
#      # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
#      group: SEATA_GROUP
#      username: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
#      application: seata-server
#      server-addr: 116.198.200.0:8848
#      group: SEATA_GROUP
#      namespace: 9b648059-4aae-4965-8cc4-6b758b4b6f73
#      username: "nacos"
#      password: "nacos"
#  client:
#    rm:
#      # 是否上报成功状态
#      report-success-enable: true
#      # 重试次数
#      report-retry-count: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
